before_install:
- pip3 install black
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: ds5oS1I+dCbAcmAazIe+DKW3h0UijOZ+sf0EmKaB844azECQJP2Z95uyrdYzyX7vrPqPtlNMsO5CCHjp3D0S0ex8nKiCMT5Z8sClQUc8Hq3NO7zGEG5pHb3OaSFslWV+FyzMV+2n03aSSGAAe9cxuPsDwjqOV3ayTy0vLzCANIkcJic8l2y0bNY1vgcgOM4ipGuOriNwVSsaq4MevciC5aSfO6h/5QGwE6euBqObBdehjB1lx6ihzBCMZDxVOYRLcrL2ddK0YB41ZJRyvE8KpSVgyHYl/6+eWhx56TO9zvJqIaAM4zst0hdO1Uu6W+Mgn/tVRCbi7UAfEbYHlKodJnomPNP9OcLtHsJ7heV8rzt0aq+Qhtf1LOqejAipxc/pGbcH4UofOuk2hH9vIpK0nxaFjkSxgUDObkXMIeZYPwaD06V9wLc32MtaFfZQcSBpcyF2BZS0I3TFkzEw2vQTp58msPu9AcJZjaIcy3x+FAKO5DAUM/L264ZGQ1FiHF9M5DbrWh3Zf/YVtmBO59MNt33Z43oLwbwmKl4F0nqoJaFLm86FH407rLIUTrvjLsBxfs8lt5AYSEWmd3jdJwrsSsx07NA2uSwkkhq0Xh9B65NrnAneeGbAyFdixUTBVR//5Ung2pO83lvYkjRaeAWR5yIkpgPExgSUkluMvG226J4=
  name: slackdump-0.1.1
  tag_name: 0.1.1
  true:
    repo: deep-compute/slackdump
- provider: pypi
  distributions: sdist bdist_wheel
  server: https://upload.pypi.org/legacy/
  user: deepcompute
  password:
    secure: r6Xdg42JUqGfeHo53EBqX2FUUlLs4VUWwH9qroDm0hfK+BZke9JNQ1YHiB9JFxAvdnF/nm+NtVi8mhyG+S8TUSccLUsbPjktY9FTGCrQJQrDRP5xO+sYERuymVSvnpPmcEXTADwsfhLj9plHMiy0B+4GnNp+/6aRniEOzKp00jEXYT1/5zYm+kZKWMX6bhq+BItnEeLOQTQE9MCXn8SEGZmSOCA/ICnW5fsFUTd+ifjz+pwWHVdjtNq1aNiwL2qovfptg//GdW5BgJkveopLgHaZjNCjbFqtKlMXDkjmyPWTw8DkQStfy5oTXkhHHqIUx9eOA0n+29P2JeeYsR4Il3eUeo40JrwLGH4UCn7iACdwCYFTI9iJUv+/4X/NDQEVqlk1F1aHg02+qIOSnNRd/hDfqz++uD50AtvWTVhPIYjrh86yFU3PTDGNa9Pj2K3W46cYyd386LdDVh/41pG/cwWyHM0jyITYc/UKtRBHxIEhd2SrU8xIB8uDMmBji9ss+VGW5BiGpaqVb30BnDYwlZLHCq3RzSqGkfUM0zyQOXpa6xOaRllm62wUPXASNENfjFxusw2BnwUBWwQ/1KaMy32LYzD91NVn8B1GvtjpPWU7fWAikt0qB8zbb55zDEWsAynJVu0XDyW1r6OiSKD5Gok1Wq4Z6VAsHhDXOrHAPac=
  true:
    branch: master
    tags: true
install:
- pip install .
language: python
python:
- '2.7'
script:
- black --check .
- python setup.py test
